### ISSUE TITLE
Test with-cairo branch on additional Mac machines

### ISSUE THREAD

**Issue by annakirkpatrick** [gtDMMB/RNAStructViz#10]
At present, we have confirmed correct installation and execution on Iris's MacBook. Christine will try it on her Mac. We would also like to ask Torin and Svetlana to test on their machines.

I am self assigning, as I will handle reaching out to Torin and Svetlana. Assigning Christine because her computer is one of our test cases.

**Comment by annakirkpatrick** [comment]
Send email to Torin and Svetlana requesting their help.

**Comment by annakirkpatrick** [comment]
Our new undergraduate researcher Justin Deal has a MacBook. We installed from the Homebrew recipe this morning. Install was successful but did bring up a few issues, namely:
*where are the sample structures?
*The default color scheme appeared to be purple and white. This may be simply an issue of the latest commits not having been added to the homebrew install target.

**Comment by maxieds** [comment]
The **with-cairo** branch has long since been merged to **master** via a PR. Cleaning up the issues page by closing this...
