### ISSUE TITLE
Evaluate color themes and select a default

### ISSUE THREAD

**Issue by annakirkpatrick** [gtDMMB/RNAStructViz#11]
A decision needs to be made about a good default color theme before we publish this work.

**Comment by maxieds** [comment]
Without loss of generality (there are many other options we have toyed with(, the "approved" list of 6-7 themes spec'ed out and OK;ed by Christine for includsion in the default app stands at the following options. Each image's respective theme can be identified by the name in the dialog box in the middle right. There is still some debate and active question by Anna and myself as to which of the more vanilla themes should actually be set to the first-time default theme which users will see after installing the program.

![screenshot at 2019-01-09 17-46-40](https://user-images.githubusercontent.com/22165688/50934669-5696f000-1437-11e9-8678-accd3e8b6505.png)
![screenshot at 2019-01-09 17-47-33](https://user-images.githubusercontent.com/22165688/50934670-5696f000-1437-11e9-907a-9c95baa13a94.png)
![screenshot at 2019-01-09 17-47-52](https://user-images.githubusercontent.com/22165688/50934671-5696f000-1437-11e9-8e73-643d622c75cf.png)
![screenshot at 2019-01-09 17-48-43](https://user-images.githubusercontent.com/22165688/50934672-5696f000-1437-11e9-9c0f-d37999fbdf63.png)
![screenshot at 2019-01-09 17-49-06](https://user-images.githubusercontent.com/22165688/50934673-5696f000-1437-11e9-8093-adf4692f854e.png)
![screenshot at 2019-01-09 17-49-30](https://user-images.githubusercontent.com/22165688/50934674-5696f000-1437-11e9-904a-0ad152f1e23f.png)
![screenshot at 2019-01-09 17-49-50](https://user-images.githubusercontent.com/22165688/50934675-572f8680-1437-11e9-807d-62f81fe8fde3.png)

**Comment by maxieds** [comment]
After consulting with @annakirkpatrick and @ceheitsch in several meetings, this topic has now fufilled it's purpose. The default scheme is vanilla in construction (pictured below with FLTK *gleam* widget stylings). Users who wish to "*spice up*" their usage of ``RNAStructViz`` can do so by consulting the instructions [in the WIKI](https://github.com/gtDMMB/RNAStructViz/wiki/UserThemesAndPreferences). 

![screenshot at 2019-03-02 12-27-22](https://user-images.githubusercontent.com/22165688/53685285-91562f80-3ce6-11e9-94ff-0dcda144589d.png)
