### ISSUE TITLE
Fill in wiki

### ISSUE THREAD

**Issue by annakirkpatrick** [gtDMMB/RNAStructViz#12]
Maxie has outlined a wiki describing use of RNAStructViz [here](https://github.com/gtDMMB/RNAStructViz/wiki). All sections need to be filled in.

**Comment by maxieds** [comment]
This will be necessary to complete in reasonable order before we submit the application note as intended ...

**Comment by maxieds** [comment]
Note that we need updated screenshots for the application note finalized WIKI version as much has changed about subtleties of the ``RNAStructViz`` appearance in a couple of short months.

**Comment by maxieds** [comment]
I'm calling this a closed issue now.
