### ISSUE TITLE
Clarify OS support in README

### ISSUE THREAD

**Issue by annakirkpatrick** [gtDMMB/RNAStructViz#13]
A clear statement of which OS versions we support needs to be added to the readme. Since I've discussed this with both Christine and Maxie, I will handle this edit.

**Comment by maxieds** [comment]
@annakirkpatrick 
I think that between [this introduction](https://github.com/gtDMMB/RNAStructViz/wiki#installation-quick-links) and [this clarification of procedure](https://github.com/gtDMMB/RNAStructViz/wiki/ShortAddendumForWindowsUsers) on the WIKI, this has been accomplished. Now closing the issue to prune our array-access queue...
