### ISSUE TITLE
Program closes unexpectedly on mac

### ISSUE THREAD

**Issue by irishryoon** [gtDMMB/RNAStructViz#17]
I was using RNAStructViz to visualize some structures. I had RNAStructViz open on my laptop (for about 10 minutes or so) and returned to RNAStructViz to visualize some new structures. I can successfully load new files. However, when I click on the red button (shown below), RNAStructViz closes. 

<img width="646" alt="screen shot 2019-02-11 at 2 26 52 pm" src="https://user-images.githubusercontent.com/16123954/52587918-35943700-2e09-11e9-8602-e208210e6168.png">

My terminal shows the following message:

Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffacd37210) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11797fdc8). One of the two will be used. Which one is undefined.
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: vector
Abort trap: 6

When I reopen RNAStructViz and try to visualize the same structures, it works fine. However, this issue of unexpectedly closing the program has occurred almost anytime I tried to keep RNAStructViz window open.

**Comment by irishryoon** [comment]
Hi Maxie,
I uploaded the ct files. I'm also attaching more screenshots explaining exactly what I've done before receiving the error. It turns out, I actually get these errors even without waiting for 10 minutes. I also realized that my original post marked the wrong button at which the problem occurs. 

1. I first loaded the three files "add_short_6.ct", "add_short_7.ct", and "add_short_8.ct". That gives me the following screen. I'm able to click on diagram, generate structures, and export the images. 

![screen shot 2019-02-14 at 7 56 07 am](https://user-images.githubusercontent.com/16123954/52788224-4a9ddf80-302e-11e9-8c36-e04c2c217029.png)

2. I then closed the window showing the structures. I also clicked on the "x" (marked by red box) to get rid of all the files I loaded initially. 
![screen shot 2019-02-14 at 7 56 07 am](https://user-images.githubusercontent.com/16123954/52788300-7b7e1480-302e-11e9-99e8-68e07e8c2626.png)

3. I then loaded three new files "add_1.ct", "add_3.ct", and "add_13.ct", resulting in the following screen.

![screen shot 2019-02-14 at 7 56 37 am](https://user-images.githubusercontent.com/16123954/52788331-95b7f280-302e-11e9-8696-73483a2d5742.png)

4. I can click on the red box. Nothing seems to change when I click on that button. 

![screen shot 2019-02-14 at 7 56 37 am](https://user-images.githubusercontent.com/16123954/52788419-d6177080-302e-11e9-8a1c-5016523d282b.png)
 
5. When I click on the "diagram" button, RNAStructViz closes, and I receive the error message posted earlier.  

![screen shot 2019-02-14 at 7 56 37 am 2](https://user-images.githubusercontent.com/16123954/52788455-f9dab680-302e-11e9-9307-562a148a112d.png)

Files:
[ct_files.zip](https://github.com/gtDMMB/RNAStructViz/files/2865034/ct_files.zip)

**Comment by maxieds** [comment]
@irishryoon @annakirkpatrick 
I am officially on the problem today. I will report back as soon as I know how to fix the bugs in the code that are causing you biological downtime.

**Comment by maxieds** [comment]
@irishryoon 
For #4, clicking on that button should result in showing the RHS display (FolderWindow) if it is not already displayed. Since it is already showing, this is the expected behavior.

N.b., I fixed many (too many) lingering bugs that happen when closing the opened structures. I guess I really didn't test this so thoroughly while developing a few months ago. It seems to be working now in so much as I can no longer reproduce your error. This is a good thing!

I will follow up soon with instructions for how you can re-install with Brew once I have that package back working.

**Comment by maxieds** [comment]
@Iris @annakirkpatrick 
![screenshot at 2019-02-21 18-12-10](https://user-images.githubusercontent.com/22165688/53208307-537d4b00-3604-11e9-9e08-f8d92399d80f.png)

**Comment by maxieds** [comment]
@irishryoon 
Please test out the new version of StructViz:
```
$ brew uninstall rnastructviz
$ brew install gtDMMB/core/rnastructviz
```

**Comment by irishryoon** [comment]
@maxieds 
The new version resolved the issue documented!

I found a similar bug as the one documented on this issue:

<img width="650" alt="screen shot 2019-02-22 at 4 32 53 pm" src="https://user-images.githubusercontent.com/16123954/53272712-078fdc00-36c0-11e9-86d2-e54b2b0a790b.png">

If I click on the button marked by the red box, RNAStructViz closes. I get a message saying "RNAStructViz closed unexpectedly". The following is shown on my terminal:

"Floating point exception: 8"

**Comment by maxieds** [comment]
@irishryoon 
I'm on it. Like the previous bugs you reported, there is some weird unexpected behavior that comes in when you remove the last button / structure in the list. I'm looking at fixing the problem now. I will update the brew package again once I fix the error.

**Comment by maxieds** [comment]
@annakirkpatrick @irishryoon 
Just, FYI, and because this sort of thing makes me scream obscenities aloud at my terminal, the offending line of code in question was the following:
```
int nextIndex = (index + 1) % folders.size();
```
Apparently when you perform ordinary mod integer arithmetic modulo zero, it throws a **FPE / Floating Point Exception**. Now we know.

**Comment by maxieds** [comment]
@irishryoon 
The brew package has been updated with the fixes to version **v1.3.5-production**. The reinstall instructions are the same as before. Please update the package and let me know if you find any more persisting errors.

**Comment by maxieds** [comment]
Can we now close this issue and call it resolved?

**Comment by irishryoon** [comment]
@maxieds Yes, the new version works well now. Thanks Maxie!
