### ISSUE TITLE
Feature request - Clarifying the 5' and the 3' on diagram.

### ISSUE THREAD

**Issue by irishryoon** [gtDMMB/RNAStructViz#18]
It was mentioned by biologists that clarifying the 5' end and the 3' end on the diagram would be helpful. Right now, the locations of the ends of the RNA is not clear from the diagram.

**Comment by maxieds** [comment]
@irishryoon 
Which diagrams are you talking about? Can you post a screenshot showing what you want changed?

**Comment by irishryoon** [comment]
@maxieds 
I indicated a possible change in red. The idea is that it should be clear that the RNA is read from 5' -> 3' starting at the bottom of the circle in clockwise direction. 

The indication I made in red is just a suggestion. I think it would be helpful to discuss with Christine and Anna what the clearest (and aesthetically pleasing) way of indicating this information would be.

![screen shot 2019-02-23 at 11 54 34 am](https://user-images.githubusercontent.com/16123954/53289280-2b0b6300-3762-11e9-801a-349389156c66.png)

**Comment by maxieds** [comment]
@annakirkpatrick @irishryoon @ceheitsch 
How does this look? It's basically what Anna just suggested we do to denote this for new users:

![screenshot at 2019-02-24 19-38-09](https://user-images.githubusercontent.com/22165688/53308011-da802c80-386b-11e9-973c-e32c3b25e866.png)

**Comment by maxieds** [comment]
I changed the font size and centering of the "5' | 3'" string on the *Diagram Window* to the following:

![screenshot at 2019-02-24 20-31-34](https://user-images.githubusercontent.com/22165688/53309048-8aa56380-3873-11e9-83ab-e27cdb1f80ad.png)

The current version (and updated Brew package release) is now **v1.3.7-production**.

**Comment by irishryoon** [comment]
@maxieds
Looks good! Could the fonts be just a bit bigger? Thanks!

**Comment by maxieds** [comment]
@irishryoon 
Anna and I consciously wanted to make the font size of the 5'/3' marker about the same size as the text above the drop down boxes ("*Structure #*" ...). I changed it from a font size of 10 to 12 for you. Can you live with it as in the new release (screenshot below)? 

![screenshot at 2019-02-25 08-52-23](https://user-images.githubusercontent.com/22165688/53341974-ebb45200-38da-11e9-9b19-d9acde697abd.png)

**Comment by irishryoon** [comment]
@maxieds Yes, that's fine. Thank you!

**Comment by maxieds** [comment]
@annakirkpatrick @ceheitsch 
I'm still actively working on the drawing code for this. This is the symbol marker I came up with. Exact screenshot of the implementation to follow in the next hour or so (next StructViz item to fix in my queue).
![5prime3primemarker-final](https://user-images.githubusercontent.com/22165688/53672269-c3688280-3c4f-11e9-8328-f0dfeafd39fe.png)

**Comment by maxieds** [comment]
@annakirkpatrick @ceheitsch @irishryoon 
New screenshot as it stands:

![screenshot at 2019-03-01 22-03-50](https://user-images.githubusercontent.com/22165688/53676274-f4f04680-3c6d-11e9-86af-dde256cdf20e.png)

Can we officially close this issue now?

**Comment by maxieds** [comment]
@ceheitsch @irishryoon 
Closing with this as the current:
![screenshot at 2019-03-06 02-16-27](https://user-images.githubusercontent.com/22165688/53862659-09a64480-3fb6-11e9-8c3a-b47ec39b92fa.png)
