### ISSUE TITLE
CT file viewer highlighting

### ISSUE THREAD

**Issue by maxieds** [gtDMMB/RNAStructViz#20]
@ceheitsch @annakirkpatrick 
I thought I would just officially make this an issue we need to address. Christine mentioned that we should bold the first item in each pair to make it clear and user friendly to biologists who are used to this type of distinction in the pair items. Unfortunately, I was not able to find any references in the FLTK documentation which lets me bold specific lines in the *Fl_Text_Buffer* without completely re-writing the implementation (RE: no more colored highlighting would be possible). What I was able to do was add a star to the left to each first entry in the pair (see screenshot below). Does this work with you all? Note that the character choices in place of the asterisk character are somewhat limited to being standard ascii characters...
![screenshot at 2019-02-22 17-03-20](https://user-images.githubusercontent.com/22165688/53277582-8c83f100-36d2-11e9-89f4-6f8a3d7eb832.png)

**Comment by maxieds** [comment]
@annakirkpatrick @ceheitsch 
An updated screenshot is shown below:
![screenshot at 2019-02-24 19-10-41](https://user-images.githubusercontent.com/22165688/53307579-e833b300-3867-11e9-9c57-60b833e4ada2.png)

**Comment by maxieds** [comment]
@irishryoon
Would you please reinstall the Brew package to the [latest version (v1.3.6-production)](https://github.com/gtDMMB/RNAStructViz/releases/latest) and verify that the new text box at the bottom of the previous screenshot displays correctly on Mac? Thanks.

**Comment by irishryoon** [comment]
@maxieds 
It does display properly. However, the text is very small in size. 

![screen shot 2019-02-25 at 8 10 11 am](https://user-images.githubusercontent.com/16123954/53339638-ea802680-38d4-11e9-9b6c-1d7a9f7472b3.png)

**Comment by maxieds** [comment]
@irishryoon 
Please reinstall and test this out again with the latest release's new Brew package.

**Comment by irishryoon** [comment]
@maxieds 
Should I uninstall and reinstall Brew, and then try running RNAStructViz? The output posted earlier is what I got after updating Brew (without uninstalling and reinstalling)

**Comment by maxieds** [comment]
@annakirkpatrick @ceheitsch 

Closing. This is the most recent screenshot.

![screenshot at 2019-03-01 18-11-28](https://user-images.githubusercontent.com/22165688/53671709-a632b480-3c4d-11e9-92e7-72a2d54d5590.png)

**Comment by maxieds** [comment]
@irishryoon 
Yes, please do whatever you did before to get a running version of the latest software.
