### ISSUE TITLE
Homebrew site install stats and install tracking?

### ISSUE THREAD

**Issue by maxieds** [gtDMMB/RNAStructViz#26]
Seeing as we're trying to make the user's (on a Mac) life as simple as possible with respect to installing ``RNAStructViz``, I think it's prudent that we investigate a good way to track the number of installs of our Homebrew taps (including the custom FLTK v1.4.x install on the Mac platform which can have other uses). Note that the default tracking done by Homebrew on its stock packages does not seem to apply here. This is on my active TODO list of things to check out for the project.

**Comment by maxieds** [comment]
@irishryoon
Please run the following commands and post the output of the last one on your Mac:
```
$ brew install --build-bottle gtDMMB/core/RNAStructViz
$ brew bottle gtDMMB/core/RNAStructViz
```
According to [this document](https://github.com/Homebrew/brew/blob/master/docs/Bottles.md), the last command should have some output which I will need to incorporate into the formula for our local ``RNAStructViz`` tap. 

Thanks, Iris!

**Comment by maxieds** [comment]
It appears that due to ``linuxbrew`` (Ubuntu package ``linuxbrew-wrapper``) I can actually execute the above commands for bottling our taps. Here are the relevant statistics for the two packages we currently maintain on the GTDMMB site:
1. [RNAStructViz install stats]() (TODO)
2. [FLTK-WithCairo install stats]() (TODO)

**Comment by irishryoon** [comment]
@maxieds 
When I run  "brew install --build-bottle gtDMMB/core/RNAStructViz", I get the following message. In fact, it looks like I get a similar error when I just try "brew install gtDMMB/core/rnastructviz". This will be reported on a separate issue. 

==> Installing rnastructviz from gtdmmb/core
==> Downloading https://github.com/gtDMMB/RNAStructViz/archive/v1.3.9-production
Already downloaded: /Users/irisyoon/Library/Caches/Homebrew/downloads/b969b8b867f3fd736dccc031479453fee58ebb34ab8dbf93aa1bb4077913ad92--RNAStructViz-1.3.9-production.tar.gz
==> git clone https://github.com/gtDMMB/RNAStructViz.git
==> make clean
==> make
Last 15 lines from /Users/irisyoon/Library/Logs/Homebrew/rnastructviz/03.make:
In file included from ./ConfigOptions.h:78:
./RNACUtils.cpp:48:39: error: address of overloaded function 'IsEqualDefaultCPPCheck' does not match required type 'void'
                                void *compareFunc = IsEqualDefaultCPPCheck) {
                                                    ^~~~~~~~~~~~~~~~~~~~~~
./RNACUtils.cpp:39:20: note: candidate template ignored: could not match 'bool (TSpec, TSpec)' against 'void'
static inline bool IsEqualDefaultCPPCheck(TSpec x, TSpec y) { 
                   ^
./RNACUtils.cpp:48:25: note: passing argument to parameter 'compareFunc' here
                                void *compareFunc = IsEqualDefaultCPPCheck) {
                                      ^
1 error generated.
make[1]: *** [DisplayConfigWindow.o] Error 1
1 error generated.
make[1]: *** [DiagramWindow.o] Error 1
make: *** [default] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/gtdmmb/homebrew-core/issues
