### ISSUE TITLE
Feature request -- Diagram window tick marks on the bounding circle to show relative base pair positions

### ISSUE THREAD

**Issue by maxieds** [gtDMMB/RNAStructViz#27]
I do not want to be of the hat variety that says see descriptive subject line above, so I will fill in a few details. @ceheitsch has requested this feature to clarify the relative positions of the base pairs on the circle. In particular, she notes that "*at a minimum we probably should have 'tick marks' around the [bounding diagram window] circle so that a user has some sense of the position of the pairings*".

While the arc diagram type we have implemented in ``RNAStructViz`` has the pro of standardizing the way we compare overlapping (nested, disjoint) pairs across multiple *structures* (rather than CT file samples of the same organism), this semi-standardized viewpoint is subject to scaling: the more pairs (base pairs, sequence entries for the structure) present in the data file for an organism, the tighter we will need to in-space these numbered entries around the circle. 

This feature should be of help to biologists in interpreting the diagrams our software can produce in practice. This is much like issue #18 posted by @irishryoon which is a feature specifically requested as feedback from our users. Note that other feature requests are highly suggested as **new issues** by our active user base. 

**Time Estimate:** ~~2-5 hours~~ 5-7 hours of active developer time

**Comment by maxieds** [comment]
![screenshot at 2019-03-03 11-01-31](https://user-images.githubusercontent.com/22165688/53697917-3551e080-3da4-11e9-93f8-0ff9b5170d92.png)

@irishryoon @ceheitsch 
Is this formatting useful?

**Comment by irishryoon** [comment]
@maxieds That would be super helpful!

**Comment by maxieds** [comment]
@ceheitsch @irishryoon 
Closing with this as the current:
![screenshot at 2019-03-06 02-16-27](https://user-images.githubusercontent.com/22165688/53862610-debbf080-3fb5-11e9-9bbf-e232c20aeae6.png)
