### ISSUE TITLE
RNAStructViz does not install on mac

### ISSUE THREAD

**Issue by irishryoon** [gtDMMB/RNAStructViz#29]
To check out some of the updates Maxie made, I tried running the following:

brew uninstall rnastructviz
brew install gtDMMB/core/rnastructviz

I receive the following error when I try running "brew install gtDMMB/core/rnastructviz"

==> Installing rnastructviz from gtdmmb/core
==> Downloading https://github.com/gtDMMB/RNAStructViz/archive/v1.3.9-production
Already downloaded: /Users/irisyoon/Library/Caches/Homebrew/downloads/b969b8b867f3fd736dccc031479453fee58ebb34ab8dbf93aa1bb4077913ad92--RNAStructViz-1.3.9-production.tar.gz
==> git clone https://github.com/gtDMMB/RNAStructViz.git
==> make clean
==> make
Last 15 lines from /Users/irisyoon/Library/Logs/Homebrew/rnastructviz/03.make:
In file included from ./ConfigOptions.h:78:
./RNACUtils.cpp:48:39: error: address of overloaded function 'IsEqualDefaultCPPCheck' does not match required type 'void'
                                void *compareFunc = IsEqualDefaultCPPCheck) {
                                                    ^~~~~~~~~~~~~~~~~~~~~~
./RNACUtils.cpp:39:20: note: candidate template ignored: could not match 'bool (TSpec, TSpec)' against 'void'
static inline bool IsEqualDefaultCPPCheck(TSpec x, TSpec y) { 
                   ^
./RNACUtils.cpp:48:25: note: passing argument to parameter 'compareFunc' here
                                void *compareFunc = IsEqualDefaultCPPCheck) {
                                      ^
1 error generated.
make[1]: *** [DisplayConfigWindow.o] Error 1
1 error generated.
make[1]: *** [DiagramWindow.o] Error 1
make: *** [default] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/gtdmmb/homebrew-core/issues

**Comment by maxieds** [comment]
@irishryoon 
Please build the (*hopefully fixed*) [latest release](https://github.com/gtDMMB/RNAStructViz/releases/tag/v1.4.2-testing) with these commands and send me / post the output of the last command as a follow-up message:
```
$ brew install --build-bottle gtDMMB/core/RNAStructViz
$ brew bottle gtDMMB/core/RNAStructViz
```
**P.S.** That's weird that ``gcc`` on a Mac gives that error. I tried compiling with a compiler (``clang``) that we have had luck with on Mac in the past and it should pass muster there... If for some reason the above does not work, try building with the following alternate commands (and post to let me know that this is what worked):
```
$ brew install --with-clang --build-bottle gtDMMB/core/RNAStructViz
$ brew bottle gtDMMB/core/RNAStructViz
```

**Comment by irishryoon** [comment]
@maxieds 
Both methods give me error when I try "brew bottle gtDMMB/core/RNAStructViz". The error message is "Error: Formula not installed or up-to-date: gtdmmb/core/rnastructviz"

I attached my terminal outputs for both methods:
without clang
[without_clang.txt](https://github.com/gtDMMB/RNAStructViz/files/2936302/without_clang.txt)
with clang
[with_clang.txt](https://github.com/gtDMMB/RNAStructViz/files/2936303/with_clang.txt)

**Comment by maxieds** [comment]
@irishryoon 
Please first run
```
$ brew uninstall gtDMMB/core/RNAStructViz
```
and then re-run the above command(s).

**Comment by irishryoon** [comment]
@maxieds 
I ran "brew uninstall gtDMMB/core/RNAStructViz", and I get the error: "Error: No such keg: /usr/local/Cellar/rnastructviz"

I ran the above (three-line) commands anyways and I receive the same error at the last line: "Error: Formula not installed or up-to-date: gtdmmb/core/rnastructviz"

**Comment by maxieds** [comment]
@irishryoon 
If only I had a Mac to test on this would be so much easier! Please run the following and then the commands as above:
```
$ brew uninstall rnastructviz
```

**Comment by irishryoon** [comment]
@maxieds 
I again get the error "Error: No such keg: /usr/local/Cellar/rnastructviz"

**Comment by maxieds** [comment]
@irishryoon 
Based on [this forum post](https://stackoverflow.com/questions/28225045/no-such-keg-usr-local-cellar-git), what we need to do is run the following:
```
$ brew update
$ brew uninstall --force rnastructviz
$ brew cleanup -s rnastructviz
$ brew prune
$ brew install gtDMMB/core/rnastructviz
$ brew install --build-bottle gtDMMB/core/rnastructviz
$ brew bottle gtDMMB/core/rnastructviz
```
If this **still** doesn't work, then paste the output of this command so I can look at it:
```
$ brew doctor
```

**Comment by irishryoon** [comment]
@maxieds 
When I run brew prune, I get the error "Error: Calling 'brew prune' is disabled! Use 'brew cleanup --prune-prefix' instead." 
So I used "brew cleanup --prune-prefix", and it seems to work fine.

I still receive the same error at the very last line. I ran brew doctor, and I'm attaching the output here.

[brew_doctor_output.txt](https://github.com/gtDMMB/RNAStructViz/files/2937899/brew_doctor_output.txt)

**Comment by maxieds** [comment]
@irishryoon 
Let's try something else. What do you get when you run:
```
$ brew tap
$ brew tap --repair
$ brew list gtDMMB/core/rnastructviz
```

**Comment by maxieds** [comment]
@irishryoon 
**P.S.** If the above ``brew tap --repair`` command works, then you should see a new version of *RNAStructViz* to install like **v1.4.4-production**. If you do see this, please go ahead and try to run the install and bottle commands one more time...

**Comment by irishryoon** [comment]
@maxieds 
This is the output

lawn-143-215-55-187:~ irisyoon$ brew tap
gtdmmb/core
homebrew/cask
homebrew/core
lawn-143-215-55-187:~ irisyoon$ brew tap --repair
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.

lawn-143-215-55-187:~ irisyoon$ brew list gtDMMB/core/rnastructviz
Error: No such keg: /usr/local/Cellar/rnastructviz

**Comment by maxieds** [comment]
@irishryoon 
Try this now:
```
brew tap --full gtDMMB/homebrew-core https://github.com/gtDMMB/homebrew-core
```

**Comment by maxieds** [comment]
@irishryoon 
```
$ brew install gtDMMB/core/RNAStructViz
$ brew install --build-bottle gtDMMB/core/RNAStructViz
$ brew bottle gtDMMB/core/RNAStructViz
```

**Comment by maxieds** [comment]
@irishryoon 
```
$ RNAStructViz --about
==== RNAStructViz v1.4.4-production -- CT File Viewer and Structure Comparison Tool ====

ABOUT THIS APPLICATION:
   >> User Manual: https://github.com/gtDMMB/RNAStructViz/wiki
   >> Git Revision: e35b72629fa2 (e35b72629fa2fb5b9aafef6b95b89f51461b1e73) [tags/v1.3.8-production-23-g890031]
   >> Revision Date: Wed Mar 6 07:39:32 2019 -0500
   >> FLTK Library Version: 1.4.0 (API #10400)
   >> Compile-Time FLTK-Config: /home/maxie/RNA-projects/RNAStructViz/src/fltk-config
   >> Cairo Library Version: 1.15.10
   >> Target Platform: Linux (4.15.0-20-generic) [x86_64] @ penguinboxhp
   >> Local Build Time: Wed 06 Mar 2019 08:42:35 AM EST

BUG REPORT INFORMATION:
**Please include a screenshot along with this information in any bug report you submit. New issues with the application can be submitted at https://github.com/gtDMMB/RNAStructViz/issues.**
```

**Comment by irishryoon** [comment]
When I run the above, I get the following:

lawn-143-215-55-187:~ irisyoon$ $STRUCTVIZ --about
options are:
 -bg2 color
 -bg color
 -di[splay] host:n.n
 -dn[d]
 -fg color
 -g[eometry] WxH+X+Y
 -i[conic]
 -k[bd]
 -na[me] classname
 -nod[nd]
 -nok[bd]
 -not[ooltips]
 -s[cheme] scheme
 -ti[tle] windowtitle
 -to[oltips]

A window that looks like the following opens up: 
<img width="654" alt="screen shot 2019-03-06 at 3 04 00 pm" src="https://user-images.githubusercontent.com/16123954/53910509-fdf06780-4021-11e9-930c-464eca43afdf.png">

I tried adding some files as if I was running RNAStructViz, and I get the following:

<img width="796" alt="screen shot 2019-03-06 at 3 04 29 pm" src="https://user-images.githubusercontent.com/16123954/53910542-0fd20a80-4022-11e9-9a1f-5080469c4865.png">

**Comment by maxieds** [comment]
@irishryoon 
You are probably finding an out of date version of ``RNAStructViz`` we installed way (way) back before I even have the remote access Mac box for testing. Can you see what this command executes:
```
find / -iname 'RNAStructViz' 2>&1 | grep -i opt | sort
```

**Comment by maxieds** [comment]
@irishryoon 
Also, can I see the output of these commands:
```
$ brew install gtDMMB/core/rnastructviz
$ brew install --build-bottle gtDMMB/core/rnastructviz
$ brew bottle gtDMMB/core/rnastructviz
$ brew doctor
```

**Comment by maxieds** [comment]
@irishryoon 
Please also try testing the following:
```
$ brew ls --full-name | cat | grep -i rnastructviz
$ brew deps gtDMMB/core/rnastructviz | xargs brew remove --ignore-dependencies && brew missing | xargs brew install
$ brew deps gtDMMB/core/rnastructviz | xargs brew remove --ignore-dependencies && brew missing | xargs brew install --build-bottle
$ brew deps gtDMMB/core/rnastructviz | xargs brew remove --ignore-dependencies && brew missing | xargs brew bottle
```
If none of these work, we will have to talk tomorrow...

**Comment by irishryoon** [comment]
@maxieds 

When I run 

`find / -iname 'RNAStructViz' 2>&1 | grep -i opt | sort`

I don't get anything back. I then ran 

`$ brew install gtDMMB/core/rnastructviz
$ brew install --build-bottle gtDMMB/core/rnastructviz
$ brew bottle gtDMMB/core/rnastructviz
$ brew doctor`

and get the following output: 
[output_1.txt](https://github.com/gtDMMB/RNAStructViz/files/2938890/output_1.txt)

When I run 

`$ brew ls --full-name | cat | grep -i rnastructviz
$ brew deps gtDMMB/core/rnastructviz | xargs brew remove --ignore-dependencies && brew missing | xargs brew install
$ brew deps gtDMMB/core/rnastructviz | xargs brew remove --ignore-dependencies && brew missing | xargs brew install --build-bottle
$ brew deps gtDMMB/core/rnastructviz | xargs brew remove --ignore-dependencies && brew missing | xargs brew bottle`

I get the following output: 
[output2.txt](https://github.com/gtDMMB/RNAStructViz/files/2938893/output2.txt)

**Comment by maxieds** [comment]
@irishryoon 

## Try this first 

The first output file says you have unlinked kegs (packages). We're going to remove them so that they get reinstalled when running the install command for StructViz:
```
$ brew remove vim
$ brew remove ghostscript
$ brew remove cctools
$ brew remove fltkwithcairo
```
Now try updating and cleaning up packages with brew:
```
$ brew update
$ brew cleanup fltkwithcairo
$ brew cleanup rnastructviz
```
Now run:
```
$ brew tap gtDMMB/homebrew-core
$ brew install gtDMMB/core/rnastructviz
```
**At this point, stop and try to run RNAStructViz from your terminal. If it doesn't work, go to the next section below for more troubleshooting.** Otherwise, continue to try to bottle the tap of ``RNAStructViz``:
```
$ brew install --build-bottle gtDMMB/core/rnastructviz
$ brew bottle gtDMMB/core/rnastructviz
```
If this succeeds, please post the output of the last command here. 

## More troubleshooting (in the dark)

Can you post the output of this command:
```
$ brew tap
$ brew outdated
```
Finally, if nothing else works, try running this command (it may take a while, so be prepared to wait if we get to this point):
```
$ brew upgrade gtDMMB/core/rnastructviz
$ brew upgrade
```
Here's a good [reference / FAQ](https://docs.brew.sh/FAQ) on the brew command.

**Comment by irishryoon** [comment]
@maxieds 
Posting output from this morning here in case it's useful. 
[output_morning.txt](https://github.com/gtDMMB/RNAStructViz/files/2942018/output_morning.txt)

**Comment by irishryoon** [comment]
@maxieds 
Would it be possible for us to use the history function from git to create a branch of the old version of RNAStructViz? That way, I would still be able to use RNAStructViz while I wait for all the mac related issues to be resolved. 

From my initial post of this issue, we would have to look at a version before March 4th. I honestly do not know how far back into the past we need to go to have the functioning version of RNAStructViz. Does this sound like something that can be done easily?

**Comment by maxieds** [comment]
@irishryoon 
Here's how to pick a tag, let's refer to it by *&lt;GIT-TAG&gt;*:
```
git log --tags --simplify-by-decoration --pretty="format:%ai %d"
```
My best guess based on your last post would be *&lt;GIT-TAG&gt;* := **v1.3.9-production**. Then to clone, and compile that version of the StructViz software, run the following:
```
cd ~
git clone https://github.com/gtDMMB/RNAStructViz.git
cd RNAStructViz
git reset --hard <GIT-TAG>
make clean && make && sudo make install
RNAStructViz
```
Now you should be able to run as usual before the Mac *strchr* errors (to be fixed this week). Let me know if this works for you.

**Comment by irishryoon** [comment]
@maxieds 
This almost worked, but I keep getting an error at the "make" stage: ./BranchTypeIdentification.h:11:10: fatal error: 'cairo.h' file not found

I'm also attaching the terminal output after running "make". Is there an easy fix to this problem? 
[make_error.txt](https://github.com/gtDMMB/RNAStructViz/files/2954081/make_error.txt)

**Comment by maxieds** [comment]
@irishryoon 
Keep in mind that every thing else we're installing here should be the same. We are just trying to temporarily work around the broken Mac installer for ``RNAStructViz`` until you and @annakirkpatrick can get me the working Mac Mini box this week to test with. That is to say that you first need to run:
```
$ brew install cairo
$ brew install gtDMMB/core/fltkwithcairo
```
Then proceed with the ``git`` from-source install directions from above. Does it work now?

**Comment by maxieds** [comment]
@irishryoon 
Can you re-test the latest commit on your Mac (**should** fix the previous errors):
```
mkdir test
cd test
git clone https://github.com/gtDMMB/RNAStructViz.git
cd RNAStructViz
make && ./src/RNAStructViz
```
If this doesn't work, please post the compiler errors.

**Comment by irishryoon** [comment]
@maxieds 
When I run the second line, I get the following warning:

Warning: gtdmmb/core/fltkwithcairo 1.4.x-r13107 is already installed, it's just not linked
You can use `brew link fltkwithcairo` to link this version.

I then tried runing "brew link fltkwithcairo", and I get the following:

Linking /usr/local/Cellar/fltkwithcairo/1.4.x-r13107... 
Error: Could not symlink include/FL/Enumerations.H
Target /usr/local/include/FL/Enumerations.H
already exists. You may want to remove it:
  rm '/usr/local/include/FL/Enumerations.H'

To force the link and overwrite all conflicting files:
  brew link --overwrite fltkwithcairo

To list all files that would be deleted:
  brew link --overwrite --dry-run fltkwithcairo

**Comment by irishryoon** [comment]
@maxieds 
Sorry, didn't realize you had another update before writing my previous comment.

I just tried your latest suggestion. I still get an error when I type make : 

./BranchTypeIdentification.h:11:10: fatal error: 'cairo.h' file not found
#include <cairo.h>
         ^~~~~~~~~
1 error generated.

**Comment by maxieds** [comment]
@irishryoon 
I tested the Mac install process with the new remote access box. This should work to install on your machine now:
```
$ brew install -v gtdmmb/core/rnastructviz
```
Let me know if this works out so we can close the issue.

**Comment by irishryoon** [comment]
@maxieds 
It works!!!  🥇 🍾 🎆
