### ISSUE TITLE
Receive error message when quitting RNAStructViz

### ISSUE THREAD

**Issue by irishryoon** [gtDMMB/RNAStructViz#34]
When I close RNAStructViz, I receive an error message saying "RNAStructViz quit unexpectedly". My terminal has the following output:

`RNAStructViz(16926,0x1109cd5c0) malloc: *** error for object 0x73677261: pointer being freed was not allocated
RNAStructViz(16926,0x1109cd5c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6`

This is not an issue that is stopping me from using RNAStructViz. However, it is something to take care of.

**Comment by maxieds** [comment]
@irishryoon 
Can you give me a step-by-step set of instructions for how to reproduce this error? What exactly did you click to get the error message?

**Comment by maxieds** [comment]
@irishryoon 
Also, does everything else (including the new radial layout viewer) appear to work on your Mac install?

**Comment by irishryoon** [comment]
@maxieds 
The new radial layout viewer works fine. Here is how I got this error:

I used RNAStructViz to visualize secondary structures as usual. I then clicked on the red round button on the top left corner of the RNAStructViz window (shown below). I then receive an error message (very bottom picture).

Note: When I open RNAStructViz and close the window (without visualizing any arc diagrams), then I don't receive the error. It seems like I receive the error only after using RNAStructViz to visualize arc diagrams. 

<img width="651" alt="Screen Shot 2019-03-27 at 9 02 54 AM" src="https://user-images.githubusercontent.com/16123954/55077941-5807aa00-506f-11e9-9d47-1e05261d8128.png">

<img width="887" alt="Screen Shot 2019-03-27 at 9 03 04 AM" src="https://user-images.githubusercontent.com/16123954/55077995-779ed280-506f-11e9-9203-688a787a4fbf.png">

**Comment by maxieds** [comment]
@irishryoon 
Can you be even more specific? And post exact files you use to generate the error? I'm not seeing it from my testing on Linux.

**Comment by irishryoon** [comment]
@maxieds 

Sure! Here are screenshots of exactly what I clicked.

1. I loaded a ct file. For this example, I used the ct file in the following zip file. (However, I receive this error independent of what file I use)

[added_123456781221.ct.zip](https://github.com/gtDMMB/RNAStructViz/files/3014580/added_123456781221.ct.zip)

I then clicked on the red box "diagram" to visualize the secondary structure. 

<img width="650" alt="Screen Shot 2019-03-27 at 1 36 22 PM" src="https://user-images.githubusercontent.com/16123954/55099222-b5aeed00-5095-11e9-9880-e3e6b928229b.png">

2. I then clicked on the red button on the top left corner (inside the red box) to close the diagram window. 

<img width="787" alt="Screen Shot 2019-03-27 at 1 36 15 PM" src="https://user-images.githubusercontent.com/16123954/55099422-06bee100-5096-11e9-8c34-3e3296dc41de.png">

3. I then clicked on the red button on the top left corner (inside the red box) to close RNAStructViz window. 

<img width="650" alt="Screen Shot 2019-03-27 at 1 36 22 PM" src="https://user-images.githubusercontent.com/16123954/55099462-16d6c080-5096-11e9-8387-14d247e4d52f.png">

4. I then receive the error posted in this issue.

**Comment by maxieds** [comment]
@irishryoon 
Nope. Still cannot reproduce it on Linux. Thank you very much as usual though for the the thorough step-by-step instructions. I will try to see if I can get the error reproduced with the Mac OSX remote box over VNC in a couple of days. 

What version are you running? 
```
$ RNAStructViz --about
```

**Comment by irishryoon** [comment]
@maxieds No problem! I'm running v1.4.7-testing. Here is the full output when I run the command you posted. 

==== RNAStructViz v1.4.7-testing -- CT File Viewer and Structure Comparison Tool ====

ABOUT THIS APPLICATION:
   >> User Manual: https://github.com/gtDMMB/RNAStructViz/wiki
   >> Git Revision:  () []
   >> Revision Date: 
   >> FLTK Library Version: 1.4.0 (API #10400)
   >> Compile-Time FLTK-Config: /usr/local/Cellar/fltkwithcairo/1.4.x-r13107_2/bin/fltk-config
   >> Cairo Library Version: 1.16.0
   >> Target Platform: Darwin (18.2.0) [x86_64] @ macbook-pro-6.lan
   >> Local Build Time: Wed Mar 20 16:35:34 2019

BUG REPORT INFORMATION:
**Please include a screenshot along with this information in any bug report you submit. New issues with the application can be submitted at https://github.com/gtDMMB/RNAStructViz/issues.**

**Comment by maxieds** [comment]
@irishryoon 
Ok, the version is the problem. I fixed this error last week. Please re-run:
```
$ brew uninstall rnastructviz
$ brew install gtDMMB/core/rnastructviz
```

**Comment by irishryoon** [comment]
@maxieds 
Works now! Thanks Maxie
