### ISSUE TITLE
Incorrect tick marks

### ISSUE THREAD

**Issue by irishryoon** [gtDMMB/RNAStructViz#35]
The tick marks seem to be incorrect.

If you run RNAStructViz with the ct files attached to this issue, you get an image like the following.

![Screen Shot 2019-04-03 at 11 20 26 AM](https://user-images.githubusercontent.com/16123954/55490970-adf5c800-5602-11e9-8ff5-36a61189cd70.png)

If you look at the tick mark near the blue, it seems to read either 53 or 55. However, one can check from the ct file that this blue helix is supposed to range from 45 to 51. 

Similarly, the two tick marks near the red helix seem to read 15 and 68 (or possibly 60). However, according to the ct file, the red helix ranges from 65 to 66. 

[incorrect_tick_marks.zip](https://github.com/gtDMMB/RNAStructViz/files/3039395/incorrect_tick_marks.zip)

**Comment by maxieds** [comment]
@irishryoon 
Thanks for pointing this out! The effect you noticed is an unintended consequence of the way I was clipping arcs with a circular mask. I believe it is fixed now (brew package to follow):
![Screenshot at 2019-04-08 08-57-20](https://user-images.githubusercontent.com/22165688/55725850-8032c980-59dc-11e9-9908-cf81d66e9ccd.png)
You can reinstall the brew package by running:
```
brew update
brew reinstall gtDMMB/core/rnastructviz
```
Please give me about 20 minutes to get the Brew package together...
