### ISSUE TITLE
Radial view window needs to move "forward"

### ISSUE THREAD

**Issue by irishryoon** [gtDMMB/RNAStructViz#36]
I tried looking at the radial view. However, the arc diagram window is always in front of the radial view window, as shown in the screenshot below. 

I would like the radial view window to move in front of the arc diagram window, especially when I click on the radial view window. 

<img width="1159" alt="Screen Shot 2019-04-03 at 2 33 18 PM" src="https://user-images.githubusercontent.com/16123954/55503878-90822780-561d-11e9-8a76-8c18a65d119e.png">

**Comment by maxieds** [comment]
@irishryoon 
This is just now fixed in the latest release *v1.5.4*. Reinstall with:
```
brew update
brew reinstall gtDMMB/core/rnastructviz
```
