### ISSUE TITLE
RNAStructviz closes unexpectedly when using CT view

### ISSUE THREAD

**Issue by irishryoon** [gtDMMB/RNAStructViz#37]
I ran RNAStructViz on the following sequence:
[12346.ct.zip](https://github.com/gtDMMB/RNAStructViz/files/3055197/12346.ct.zip)

In the arc diagram, I dragged my mouse to zoom on a particular corner as the following picture:

![Screen Shot 2019-04-08 at 11 57 57 AM](https://user-images.githubusercontent.com/16123954/55738807-dc561780-59f5-11e9-9522-85566564b407.png)

I then pressed SHIFT + G for the CT view, and I got the following window:

![Screen Shot 2019-04-08 at 11 58 14 AM](https://user-images.githubusercontent.com/16123954/55738837-e8da7000-59f5-11e9-9da0-3c1c39dbbc45.png)

I clicked on the "display zoomed region". RNAStructViz closes unexpectedly, and I receive the following error:

![Screen Shot 2019-04-08 at 11 58 23 AM](https://user-images.githubusercontent.com/16123954/55738879-fb54a980-59f5-11e9-854f-892af4778ec2.png)

On my terminal, I receive the message

"segmentation fault :11"

**Comment by maxieds** [comment]
@irishryoon 
You are going to have to be more specific to get me to be able to reproduce this error. I followed your steps on Linux and no problems. Please see the debugging with ``llvm`` on [this WIKI page](https://github.com/gtDMMB/RNAStructViz/wiki/BugReportingAndErrors#getting-even-more-verbose-errors-with-gdb-or-lldb) and see if you can get me a backtrace, or a line number where this consistently fails on your Mac.

**Comment by irishryoon** [comment]
@maxieds 

I tried to follow the debugging steps from the wiki page. However, when I type ` lldb RNAStructViz` I get the following error:

MacBook-Pro-17:~ irisyoon$ lldb RNAStructViz
(lldb) target create "RNAStructViz"
error: '/Users/irisyoon/RNAStructViz' doesn't contain any 'host' platform architectures: x86_64h, x86_64, i386, x86_64
(lldb) run
error: invalid target, create a target using the 'target create' command


In the meantime, I'll post more screenshots showing the exact buttons that I clicked to get the error.

**Comment by irishryoon** [comment]
I started RNAStructViz and loaded the ct file as usual. I clicked on the following two red boxes to get my arc diagram.

![Screen Shot 2019-04-10 at 10 57 07 AM](https://user-images.githubusercontent.com/16123954/55889874-bfe5e680-5b7f-11e9-94eb-f386c894b85e.png)
![Screen Shot 2019-04-10 at 10 57 13 AM](https://user-images.githubusercontent.com/16123954/55889882-c2484080-5b7f-11e9-8e92-766512fc97ec.png)
![Screen Shot 2019-04-10 at 10 57 27 AM](https://user-images.githubusercontent.com/16123954/55889891-c4aa9a80-5b7f-11e9-9269-7216540a8796.png)
From the arc diagram, I dragged my mouse to create a rectangle:
![Screen Shot 2019-04-10 at 10 57 35 AM](https://user-images.githubusercontent.com/16123954/55889909-cd02d580-5b7f-11e9-8cdd-53198a508f2c.png)
I then pressed "SHIFT + G" on my keyboard. A small window popped up. I then clicked on the red button.
![Screen Shot 2019-04-10 at 10 57 46 AM](https://user-images.githubusercontent.com/16123954/55889945-ddb34b80-5b7f-11e9-859d-51fdcd020200.png)
When I press on the red button, RNAStructViz closes unexpectedly.

**Comment by maxieds** [comment]
@irishryoon 
Fixed in the latest release: *v1.5.9*. Please reinstall.
