### ISSUE TITLE
Bases location is off

### ISSUE THREAD

**Issue by irishryoon** [gtDMMB/RNAStructViz#38]
I ran RNAStructViz on the following sequence
[12346.ct.zip](https://github.com/gtDMMB/RNAStructViz/files/3055209/12346.ct.zip)

I clicked on "draw bases" to display the bases. The location of the bases are off as shown by the following:

![Screen Shot 2019-04-08 at 12 02 13 PM](https://user-images.githubusercontent.com/16123954/55739056-4d95ca80-59f6-11e9-9a04-48416cd7dd42.png)

Moreover, when I unclick "draw bases", the previous bases still appear on the window. (In fact, if I unclick "draw ticks", I experience a similar problem, where a shadow of the tick marks still appear on my window)

![Screen Shot 2019-04-08 at 12 02 19 PM](https://user-images.githubusercontent.com/16123954/55739078-58505f80-59f6-11e9-88ed-cb15271e6840.png)

**Comment by maxieds** [comment]
@irishryoon 
Fixed in *v1.5.7-testing*: 
![Screenshot at 2019-04-08 12-45-43](https://user-images.githubusercontent.com/22165688/55741875-51c4e680-59fc-11e9-811b-55dc5c3dd322.png)
Upgrade the brew package:
```
brew update && brew reinstall gtDMMB/core/rnastructviz
```
