### ISSUE TITLE
Take input in (i,j,k) notation

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#41]
To my knowledge, program does not currently take input in the form of (i,j,k) triples which is generated by some Boltzmann sampling code.  For example:
Structure        1     -60.60       0.15301E-02
    2   152     9
   12    80     3
   16    30     4
   34    74     3
   38    70     2
   41    67     6
   48    59     4
   90   121     5
   97   114     3
  102   109     2
  124   136     3
  128   132     1

**Comment by maxieds** [comment]
@ceheitsch The helix data alone is insufficient to load the sequence in *RNAStructViz*. We need a hybrid of the CT / Dot-Bracket file format data that also happens to include the helices as supplementary data (since we do not currently use these in the application directly). As requested, the documentation for the new format which should be supported shortly (ideally later on today) can be found on [this new WIKI page](https://github.com/gtDMMB/RNAStructViz/wiki/HelixTripleFileFormat).

**Comment by maxieds** [comment]
For reference, I basically copied the pairing data / helix notation lines of these files verbatim from the output of GTBoltzmann on the profiling webapp production webpage, and used the same conventions as in Dot-Bracket files for the first two lines with a comment line followed by the string of bases. For example: 
```
> Sequence file comment goes here
CAAAAGCACCAGGGGUGCUUGAACCAGGAUAGCCUGCGAAAAGGCGGGCUAUCCGGGACCAGGCUGAGAAAGUCCCUUUGAACCUGAACAGGGUAAUGCCUGCGCAGGGAGUGUGCAGUUUUUUUUUU
.....((((((((((((((((..((.(((((((((((......))))))))))).))..)))))..)......)))).))..((((..((((......))))..))))....))))............	-49.4	6 116 4, 10 80 2, 12 77 4, 16 67 1, 17 64 5, 24 57 2, 27 54 11, 83 108 4, 89 102 4, 
.....(((((((((..(((((..((.(((((((((((......))))))))))).))..))))).........)))).....((((..((((......))))..))))..).))))............	-52.9	6 116 4, 10 111 1, 11 77 4, 17 64 5, 24 57 2, 27 54 11, 83 108 4, 89 102 4, 
.....((((((((((.(((((..((.(((((((((((......))))))))))).))..))))).((.....))))))))..((((..((((......))))..))))....))))............	-53.9	6 116 4, 10 80 6, 17 64 5, 24 57 2, 27 54 11, 66 74 2, 83 108 4, 89 102 4, 
.....(((((.(((..(((((..((.(((((((((((......))))))))))).))..)))))(......).)))......((((..((((......))))..))))..).))))............	-50.8	6 116 4, 10 111 1, 12 76 3, 17 64 5, 24 57 2, 27 54 11, 65 72 1, 83 108 4, 89 102 4, 
.....((((((((((.(((((..((.(((((((((((......))))))))))).))..))))).((.....))))))))..((((..((((......))))..))))....))))............	-53.9	6 116 4, 10 80 6, 17 64 5, 24 57 2, 27 54 11, 66 74 2, 83 108 4, 89 102 4, 
.....((((((((((....((..((.(((((((((((......))))))))))).))..))((((.....))))))))))..((((..((((......))))..))))....))))............	-52.2	6 116 4, 10 80 6, 20 61 2, 24 57 2, 27 54 11, 62 74 4, 83 108 4, 89 102 4, 
.....((((((((((((((((..((.(((((((((((......)))))))))))))...))))).......)))))).....((((..((((......))))..))))..).))))............	-51.9	6 116 4, 10 111 1, 11 77 6, 17 64 5, 24 56 2, 27 54 11, 83 108 4, 89 102 4, 
...((((((((((((.(((((..((.(((((((((((......))))))))))).))..)))))........))))).....((((..((((......))))..))))..).))))..))........	-48.8	4 120 2, 6 116 4, 10 111 1, 11 77 5, 17 64 5, 24 57 2, 27 54 11, 83 108 4, 89 102 4, 
```

**Comment by maxieds** [comment]
@ceheitsch As of the latest commit, this feature is implemented. A Homebrew package for Mac OSX is soon to follow.
