### ISSUE TITLE
clarifying file structure for "helix triple format"

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#44]
First, let's limit it to one structure (for the time being at least) since we don't want someone to try to load too many.

Format:
">" File information line (as in fasta, etc)
Sequence string
List of (i,j,k) triples.

(The quotes are only because of markdown formatting issues.)

Should accept when triples are all in one line like this:
6 116 4, 10 80 2, 12 77 4, 16 67 1, 17 64 5, 24 57 2, 27 54 11, 83 108 4, 89 102 4,

Should also accept when triples are one per line like this:
6 116 4, 10 80 2, 12 77 4, 16 67 1, 17 64 5, 24 57 2, 27 54 11, 83 108 4, 89 102 4,

This is an example of what an sfold out file looks like:
(i j k): helix formed by base pairs i-j, (i+1)-(j-1),...,(i+k-1)-(j-k+1)

Structure        1     -35.00       0.59688E-02
    1   115     8
   14    66     2
   16    63     6
   26    54     3
   29    49     4
   68   104     2
   71   101     2
   77    95     1
   80    92     5
Structure        2     -36.00       0.18584E-01
    1   115     8
   16    63     6
   26    54     3
   29    49     4
   33    43     2
   67   105     3
   77    95     1
   80    92     5
Structure...

This is an example of what a gtboltzmann output looks like:
.....((((((((((((((((..((.(((((((((((......))))))))))).))..)))))..)......)))).))..((((..((((......))))..))))....))))............        -49.4   6 116 4, 10 80 2, 12 77 4, 16 67 1, 17 64 5, 24 57 2, 27 54 11, 83 108 4, 89 102 4, 
.....(((((((((..(((((..((.(((((((((((......))))))))))).))..))))).........)))).....((((..((((......))))..))))..).))))............        -52.9   6 116 4, 10 111 1, 11 77 4, 17 64 5, 24 57 2, 27 54 11, 83 108 4, 89 102 4, 
.....((((((((((.(((((..((.(((((((((((......))))))))))).))..))))).((.....))))))))..((((..((((......))))..))))....))))............        -53.9   6 116 4, 10 80 6, 17 64 5, 24 57 2, 27 54 11, 66 74 2, 83 108 4, 89 102 4, 

A structure from a gtboltzmann sample can be easily put into dotbracket format.  There's no easy conversion from the (i,j,k) triples to a format accepted by RNAStructViz.

**Comment by maxieds** [comment]
@ceheitsch I believe that just the triple data alone is insufficient to encode all of the pairing data that is contained in the DotBracket format. Correct me if I'm wrong, but the changes you are proposing will not have enough information for us to create the arc diagrams.

**Comment by maxieds** [comment]
@ceheitsch Can you please respond to the previous message? So we can get this issue handled and on the closed list?

**Comment by ceheitsch** [comment]
@maxieds Why don't you think there's enough information in the triplets if the file also includes the sequence?  In particular, instead of just asserting that it will fail, what is your example that illustrates the problem?

**Comment by maxieds** [comment]
@cheitsch Perhaps I'm misunderstanding the notation for the triples. I was under the impression when I wrote some of the profling code that the triples do not necessarily correspond to contiguous DotBracket symbols of ``(/)``. So for example, we could have a triple where the enclosing open/close parentheses have unpaired '.' bases contained between them. It seems to me that if we allow this case, just the triples and a string for the base characters is insufficient to glean all of the data we can get from the CT file format. Whereas, GTBoltzmann output is more complete. Correct me if I'm off here.

**Comment by maxieds** [comment]
@ceheitsch I believe I see the error in my reasoning from the previous post. The current plan is to implement a new version of the Helix Triple File Format Standard, and keep (rename) the old one to GTBoltzmann (.gtb) to distinguish. Will keep you posted on the status.

**Comment by ceheitsch** [comment]
@maxieds  Confirming that a helix triple (i,j,l) means exactly the k contiguous base pairs (i,j), (i+1, j-1), \ldots, (i+k-1, j-k+1).  You may be thinking of "stems" or "consolidated helices" which is a very different matter (and one we're not going to worry).

**Comment by maxieds** [comment]
@ceheitsch As it turns out, the corresponding parser in this case is easier than what I did to input the GTBoltzmann format files, which required some maneuvering with stacks. This seems like you just should parse the input helices in order, and set the corresponding DB notation as we go. 

When you get the file permissions issues fixed in the previous thread, would you spot check the sample *.helix* file to make sure that it is correct? The documentation for the [GTBoltzmann file format](https://github.com/gtDMMB/RNAStructViz/wiki/GTBoltzmannFileFormat) is renamed in the WIKI pages.

**Comment by maxieds** [comment]
@ceheitsch The specification for the [triple file format](https://github.com/gtDMMB/RNAStructViz/wiki/HelixTripleFileFormat) is now in draft form on the WIKI page. I am going to start on writing the parser for these files. Hopefully we can test next week.

**Comment by maxieds** [comment]
I'm going to close this now since both variants of the helix format have been implemented in the latest RNAStructViz release.
