### ISSUE TITLE
"GTBoltzmann" file format?

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#53]
Does RNAStructViz really accept multiple structures in a single input file?  The wiki suggests this is so for the "GTBoltzmann" file format, but that is inconsistent with the FAQ.    Since GTfold is not being actively maintained, this file format is confusing.

**Comment by maxieds** [comment]
@ceheitsch 
This is now resolved in the upcoming commit I'm about to push as we discussed today.
