### ISSUE TITLE
open more than one diagram windows

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#54]
Program crashes if trying to open second diagram window.

Assertion failed: (s->stack->next != NULL), function CGGStackRestore, file /BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreGraphics/CoreGraphics-1265.10/CoreGraphics/Context/CGGStack.c, line 77.
Abort trap: 6

**Comment by ceheitsch** [comment]
Quits unexpectedly even after closing first diagram window.

**Comment by maxieds** [comment]
@ceheitsch Will get back to this issue once I'm done studying for my upcoming exam on Tuesday of next week.

**Comment by maxieds** [comment]
This doesn't happen on Linux... Attempting to debug the issue on Mac.

![Screenshot at 2019-11-15 19-16-12](https://user-images.githubusercontent.com/22165688/68984100-6829f080-07dc-11ea-8276-7ed2ba55815e.png)

**Comment by maxieds** [comment]
@ceheitsch This appears to either be a pure Cairo library or FLTK (with cairo) library phenomenon on Mojave (Mac OSX 10.14.x). I'm currently working on posting to the FLTK core developers group to see if we can get this patched. Will keep you posted.

**Comment by maxieds** [comment]
@cheitsch: 
As you can see [here](https://groups.google.com/forum/?nomobile=true#!topic/fltkcoredev/bXyhlnWP3_s), this problem still persists in Mac OSX 10.14.x. I'm trying to work with the FLTK core developer for Mac to get a patch for this. Until then, do you want me to just disable this crash by insisting that only one subclass of a ``Fl_Cairo_Window`` can be opened at once on this release of of Mac OSX? It's a total hack, and will make the code uglier, but it should save some potential crashes as we are looking at sending out the testing emails soon.

**Comment by maxieds** [comment]
@cheitsch:
Not quite sure why it works, but removing the ``Fl::cairo_cc`` and ``Fl::cairo_make_current`` references makes it not crash when having multiple instances of a subclass of ``Fl_Cairo_Window`` open. Your office box should have the new **v1.9.6-testing** release re-installed on it soon today.

**Comment by ceheitsch** [comment]
Reinstalled on laptop myself.  Still crashing:

mathm2334:~ gtmath$ /usr/local/opt/rnastructviz/bin/RNAStructViz 
Assertion failed: (s->stack->next != NULL), function CGGStackRestore, file /BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreGraphics/CoreGraphics-1251.12/CoreGraphics/Context/CGGStack.c, line 77.
Abort trap: 6

**Comment by maxieds** [comment]
Ok, can you run a couple of diagnostics or me:
* What is the version of RNAStructViz printed when you run ``RNAStructViz --about``?
* What is the output of ``sw_vers`` on your Mac?

**Comment by ceheitsch** [comment]
Except that it may be that it wasn't updated to v1.9.6-testing.  Investigating now.

**Comment by maxieds** [comment]
Right. That's what the first point was hinting at diagnosing... Rev. v1.9.6 doesn't crash out on the remote server box anymore.

**Comment by ceheitsch** [comment]
All instructions for reinstalling were followed.  So the fact that it didn't update may itself be a problem.

**Comment by maxieds** [comment]
@ceheitsch 
The procedure I follow is to run the following two commands:
```
$ brew update
$ brew reinstall gtdmmb/core/rnastructviz
```
This has always worked for my used case. What sequence of update commands did you run?
