### ISSUE TITLE
Make default directory a user preference

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#55]
Ideally, there would be some way to specify the default directory where structure files are stored.

**Comment by maxieds** [comment]
@cheitsch 
There is already a setting for the search path where sample structures are loaded. Is this what you are looking for? Please close the issue if so:

![Screenshot at 2019-11-15 19-09-59](https://user-images.githubusercontent.com/22165688/68983964-ca362600-07db-11ea-8ad8-b6ae384a1c01.png)

**Comment by maxieds** [comment]
@ceheitsch 
Added the [FAQ entry](https://github.com/gtDMMB/RNAStructViz/wiki/FAQ#can-i-change-the-default-directory-where-rnastructviz-searches-for-structure-files-what-about-updating-default-save-directories-for-exported-files-like-png-images-and-csv-stats-output) you requested for documenting this feature. I'm going to now consider it a closed issue. For the other issues you noted today, I will tag them for you to close in the coming weeks.
