### ISSUE TITLE
crash after closing statistics window

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#58]
mathm2334:~ gtmath$ /usr/local/opt/rnastructviz/bin/RNAStructViz 
 ⛔ ERROR: Handling unexpected SEGFAULT (SIGSEGV) signal.

.########..##....##....###.....######..########.########..##.....##..######..########.##.....##.####.########
.##.....##.###...##...##.##...##....##....##....##.....##.##.....##.##....##....##....##.....##..##.......##.
.##.....##.####..##..##...##..##..........##....##.....##.##.....##.##..........##....##.....##..##......##..
.########..##.##.##.##.....##..######.....##....########..##.....##.##..........##....##.....##..##.....##...
.##...##...##..####.#########.......##....##....##...##...##.....##.##..........##.....##...##...##....##....
.##....##..##...###.##.....##.##....##....##....##....##..##.....##.##....##....##......##.##....##...##.....
.##.....##.##....##.##.....##..######.....##....##.....##..#######...######.....##.......###....####.########

==== 🧬  RNAStructViz v1.9.6-testing -- RNA Secondary Structure Comparison Multi-Tool ====

ABOUT THIS APPLICATION:
 >> Git Revision ..............................  [Wed Nov 20 13:49:27 2019]
 >> Revision Date ............................. Darwin (18.5.0) [x86_64] @@ mathm2334
 >> FLTK Library .............................. 1.4.0 (API #10400)
 >> FLTK-Config ............................... 
 >> Cairo Library ............................. 1.16.0
 >> Target Platform ........................... /usr/local/Cellar/fltkwithcairo/fltk-1.4.x-20191115-ee9ada96_4/bin/fltk-config
 >> Local Build Time .......................... 
 >> RNAStructViz Launch Path Command .......... /usr/local/opt/rnastructviz/bin/RNAStructViz
 >> Current Working Directory (CWD) ........... /Users/gtmath
 >> Active System User (From ENV) ............. gtmath

============================================================================================

BUG REPORT INFORMATION:
** Please include a screenshot along with this information in any bug report you submit.
   New issues with the application can be submitted by following the instructions at
   « https://github.com/gtDMMB/RNAStructViz/wiki/BugReportingAndErrors » **

**Comment by maxieds** [comment]
@ceheitsch 
Repeating, as a reminder for you in a couple of weeks, that this crash needs to be testing / tends to happen after exporting the generated stats to CSV file in the last tab of the window. I was unable to reproduce it exactly myself. Still planning to beat the tar out of my source code on a Mac for you this week to induce breakage. Tagging the issue for you to close.

**Comment by ceheitsch** [comment]
@maxieds I was trying out different comparisons.  What happens if you try exporting before and after changing something?

**Comment by maxieds** [comment]
@ceheitsch 
Exporting, then changing the reference structure, re-calculating, and then exporting again definitely will cause a crash on my Mac OSX box. I'm trying to reproduce the conditions on Linux first. Will then backport a fix to Mac OS once the crash cannot be reproduced on my development box.

**Comment by maxieds** [comment]
@ceheitsch 
The lastest push into the development code should fix the issue. There were a couple of bugs that I made code patches to fix. When I add the next release (which should bring things to **v1.9.9-testing**), this issue should be fixed on Mac. I will try to do that sometime later this morning. For right now, I have one more code tweak I want to add to the select all functionality in the "*Load Files*" dialog. Once I'm done with that (and testing), you can test the newest release on your Mac laptop. This should provide a stable version of StructViz on both Mac and Linux.

Happy Turkey Day!

**Comment by ceheitsch** [comment]
Fixed!
