### ISSUE TITLE
reopening CT viewer gives blank screen

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#60]
First viewing of pairing data is good.  After closing window, reopening is blank.

**Comment by maxieds** [comment]
@ceheitsch 
I was able to reproduce this untested behavior on Linux. It is now fixed there. I expect the Mac variant of the bug to be fixed similarly. Tagging this issue for you to close when you regain post-holiday bandwidth for the task.

**Comment by ceheitsch** [comment]
@maxieds  Please verify your expectation for Mac behavior by testing it under OSX.

**Comment by ceheitsch** [comment]
@maxieds Removing request for review until you have tested it under OSX.

**Comment by maxieds** [comment]
@ceheitsch 
Tested on Mac OSX. Verified new code is working. Please upgrade to a release of RNAStructViz >= **v1.9.8-testing**, test for yourself, and then close out the issue thread. Thanks.
