### ISSUE TITLE
Removing folders 

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#61]
Generates blank rectangle.  Or junk character string.

**Comment by maxieds** [comment]
I was not able to directly reproduce your error. But killing all of the loaded folders did cause another crash when re-clicking the "*Load Files*" button. I'm reproducing the detection instructions here in case I ever need to find them quickly again (from [the man page](http://www.gnu.org/s/libc/manual/html_node/Heap-Consistency-Checking.html#Heap-Consistency-Checking) noted in [this post](https://stackoverflow.com/questions/3100193/segfaults-in-malloc-and-malloc-consolidate)):

> Another possibility to check for and guard against bugs in the use of malloc, realloc and free is to set the environment variable MALLOC_CHECK_. When MALLOC_CHECK_ is set, a special (less efficient) implementation is used which is designed to be tolerant against simple errors, such as double calls of free with the same argument, or overruns of a single byte (off-by-one bugs). Not all such errors can be protected against, however, and memory leaks can result. If MALLOC_CHECK_ is set to 0, any detected heap corruption is silently ignored; if set to 1, a diagnostic is printed on stderr; if set to 2, abort is called immediately. This can be useful because otherwise a crash may happen much later, and the true cause for the problem is then very hard to track down.

**Comment by ceheitsch** [comment]
@maxieds Did you try to reproduce it under OSX?

**Comment by maxieds** [comment]
@ceheitsch 
The problem was present under Linux too as it turns out. I re-wrote some of the widget accounting structure code to make sure everything is getting deleted, and exactly once. It seems to work after my debugging attempts on Linux now (which is a good first sign). I will work on checking that the fixes I have for Linux now remove the error on Mac.

**Comment by maxieds** [comment]
@ceheitsch 
Tested on Mac OSX. Verified new code is working. Please upgrade to a release of RNAStructViz >= **v1.9.8-testing**, test for yourself, and then close out the issue thread. Thanks.

**Comment by maxieds** [comment]
FYI, I added the runtime export for glibc to the [bug reporting page](https://github.com/gtDMMB/RNAStructViz/wiki/BugReportingAndErrors#an-optional-bash-export-to-print-verbose-information-on-heap-allocation-and-memory-access-errors). See also my request for input about the possibility of leaving in compiler flags for debugging-type memory checking [here](https://github.com/gtDMMB/RNAStructViz/issues/57#issuecomment-559589661). In the abscence of a good stacktrace, which even well read and informed users are unlikely to report with their issues on unexpected crashes in StructViz, it's almost impossible to get a good idea of where the crash is occuring. Especially if it is on the order of a race condition error in the code that happens only every N % 15 times the user runs the application.

**Comment by ceheitsch** [comment]
Unable to reproduce problem this problem, but found a different one.  Will close issue and open a new one.
