### ISSUE TITLE
Feature request: Load sequences from NCBI database lookups

### ISSUE THREAD

**Issue by maxieds** [gtDMMB/RNAStructViz#62]
We can search through a plethora of NCBI database results by doing a web request. Moreover, @maxieds has already obtained permission from the maintainers of these database listings to generate an API key specificially for doing lookups with the RNAStructViz application. We could then add another load-type button to the LHS MainWindow navigation that will bring up a dialog to search for structures from the NCBI databases by: keyword, sequence latin names, and accession numbers. 

@cheitsch:
Is this of enough use for me to look into coding up the implementation for this over the weekend before the testing emails go out? Opinionation about how the implementation should go is of course always welcome...

**Comment by ceheitsch** [comment]
Please *don't* make any significant changes to the "beta release" code base.  We need a stable code base for the testers to play with, and it absolutely needs to be stable while the paper is under review.
