### ISSUE TITLE
Duplicate structure checking

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#66]
Load all test files though "Select All Files."   Delete "E.coli" folder.  Choose "Select All Files" again.  E.coli loads properly.  H.sapiens does not load again (correctly).  But the number of C.elegans and of "No.#3 (BOLTZ)" have changed, which they should not.

**Comment by maxieds** [comment]
@ceheitsch 
The numbers on the folders that do not have good suggestions for a naming scheme from the file meta data are **intentionally** re-numbered each time. This is to emphasize a unique scheme for naming the folders. Not doing so would also mean that we would have to keep track of the sequence (``RNAStructure*``) of all previously loaded sequences. This is impractical! Additionally, once a folder is deleted, we should assume that the context moves on (again with the unique naming scheme justification...). 

I will look to see if I can reproduce your *H. sapiens* error.

**Comment by maxieds** [comment]
Actually, upon re-reading, there wasn't an error. My bad. Let's close the issue now since this is actually not an error but an intentional design *feature* made by the developers.

**Comment by ceheitsch** [comment]
Seems to be directly related to the Boltzmann file format.  Other formats are recognized by the program if they have already been loaded, i.e. there is a command line "STATUS" message indicating the duplicate files.  However, the number of files in the "No. #1 (BOLTZ)" folder increased from 8 to 16.

**Comment by maxieds** [comment]
@ceheitsch 
This has been tested and verified as now working on Linux and Mac. Please upgrade to **v2.0.8-testing** to see the changes...

**Comment by ceheitsch** [comment]
Confirming number of structures loaded stays correct now.
