### ISSUE TITLE
Dashed box disappears when clicking in diagram window

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#67]
From memory this was a "known limitation" but I don't see it listed on the current wiki page.  If this is still the expected behavior, then please add back https://github.com/gtDMMB/RNAStructViz/wiki/KnownLimitations

**Comment by maxieds** [comment]
It was noted on the [FAQ page](https://github.com/gtDMMB/RNAStructViz/wiki/FAQ#why-does-the-zoom-box-in-the-diagram-window-disappear-when-i-refocus-the-window). Going ahead and adding also to the known limitations page.

**Comment by maxieds** [comment]
Now [here](https://github.com/gtDMMB/RNAStructViz/wiki/KnownLimitations), so closing this easy issue.
