### ISSUE TITLE
"CT view operation failed.  Try zooming again?"

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#69]
Got error message, but file viewer opened --- just not in the right place.  See screenshot.  Necessary files also attached.

![Screen Shot 2019-12-04 at 2 53 51 PM](https://user-images.githubusercontent.com/43553267/70176273-3521a100-16a6-11ea-9475-21d1c24ba4ce.png)

[ba00023_b.tar.gz](https://github.com/gtDMMB/RNAStructViz/files/3923723/ba00023_b.tar.gz)

**Comment by maxieds** [comment]
@ceheitsch 

The logic in the code, from what I can see, should not have let this happen. Nonetheless, my best guess at what happened in your run instance, is that there were multiple key presses, or perhaps you were moving the mouse while you pressed the key combination (?), that were handled simultaneously. Then the trigger for the error could have gotten called in one call to ``DiagramWindow::handle``, causing the ``fl_alert`` dialog message to get displayed, and then shortly after, another (valid) call to handle made the CT viewer window show on screen as expected. Either way, there is now a static boolean variable that it getting atomically set in the static error display code that should prevent this from happening again. Closing the issue for completeness. Feel free to re-open it if you can consistenly generate this behavior...
