### ISSUE TITLE
Error when restarting

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#70]
Cleared "rm -rf .RNAStructViz/" and "rm -rf ~/RNAStructViz".  Still get:

mathm2334:~ gtmath$ /usr/local/opt/rnastructviz/bin/RNAStructViz 
ERROR: Unable t create directory "/Users/gtmath/.RNAStructViz/AutoLoad/" ... Skipping autoloading of structure files
Local autoload directory creation error: Undefined error: 0

**Comment by maxieds** [comment]
@ceheitsch 
This should be fixed in the currently committed source code. You can upgrade to (the upcoming) **v2.0.8-testing** release on Monday to verify that this fix is in place and working on your local Mac machines.

**Comment by ceheitsch** [comment]
No error messages now after deleting folders and restarting program.
