### ISSUE TITLE
<shift+G> now causing segfault

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#74]
Diagramed 3 H.sapiens structure.  Used selection box.   <shift-G> results in:

ERROR: Handling unexpected SEGFAULT (SIGSEGV) signal.

+-+-+-+-+-+-+-+-+-+-+-+-+
|R|N|A|S|t|r|u|c|t|V|i|z|
+-+-+-+-+-+-+-+-+-+-+-+-+

==== 🧬  RNAStructViz v2.2.0-testing -- RNA Secondary Structure Comparison Multi-Tool ====

ABOUT THIS APPLICATION:
 >> Git Release Type .......................... BETA-TESTING
 >> Git Revision ..............................  [/usr/local/Cellar/fltkwithcairo/fltk-1.4.x-20191115-ee9ada96_5/bin/fltk-config]
 >> Revision Date ............................. Darwin (18.5.0) [x86_64] @@ mathm2334
 >> FLTK Library .............................. 1.4.0 (API #10400)
 >> FLTK-Config ............................... 
 >> Cairo Library ............................. 1.16.0
 >> Target Platform ........................... Wed Dec 11 12:46:39 2019
 >> Local Build Time .......................... 
 >> RNAStructViz Launch Path Command .......... /usr/local/opt/rnastructviz/bin/RNAStructViz
 >> Current Working Directory (CWD) ........... /Users/gtmath
 >> Active System User (From ENV) ............. gtmath

**Comment by maxieds** [comment]
Should be fixed in testing release **v2.2.1-testing**, which should be out later today. I will wait for @ceheitsch to test on her Mac and verify before closing the issue.

**Comment by ceheitsch** [comment]
Working now (v2.2.2-testing).
