### ISSUE TITLE
duplicate structures in different formats and/or names will be loaded

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#75]
Add a note to the wiki (perhaps under "Known Limitations"...?) that while RNAStructViz will not load duplicate *FILES*  --- by default --- it will load the same structure in different formats and/or file names.  An example is: 
5S_S.cerevisiae_GTfold.ct
5S_S.cerevisiae_UNAfold.ct
5S_S.cerevisiae_UNAfold.dot

The current behavior seems reasonable to me.  Just want to document it.

**Comment by maxieds** [comment]
@ceheitsch 

The documentation in the WIKI has been updated in the following places:
* On the [known limitations](https://github.com/gtDMMB/RNAStructViz/wiki/KnownLimitations) page as point **(7)**; and
* On the linked [FAQ](https://github.com/gtDMMB/RNAStructViz/wiki/FAQ#why-does-rnastructviz-load-duplicate-secondary-structures) page entry.

Note that there are a couple of minor implementation issues to make the WIKI behavior correct. These will be incorporated into release **v2.2.1-testing* when it is tagged later today.

**Comment by ceheitsch** [comment]
Looks good; thanks.
