### ISSUE TITLE
"calculate" button in statistics window not available if sequences selected by buttons

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#77]
Choose folder (C. elegans).  Open statistics window.  Choose reference structure (say first one).  

(1) Click "Compare All" button.  Calculate works.
(2) Change reference structure.  Calculate works.  
(3) Deselect last two structures from list under "Structures for Comparison:"  Calculate button now non-functional.

Close statistics window.  Reopen.  Choose same reference structure.
(4) Choose last two structures from list under "Structures for Comparison:"  
Calculate button stays 'greyed out'/non-functional.
(5) Click "Compare All" button.  Calculate button stays 'greyed out'/non-functional.

**Comment by maxieds** [comment]
@ceheitsch 
Working on it now. Should be fixed by the time I release **v2.2.1-testing**.

**Comment by maxieds** [comment]
@ceheitsch 
Proposed fix tested / verified by me on Mac.

**Comment by ceheitsch** [comment]
Works for me too.
