### ISSUE TITLE
duplicate text written in statistics window

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#78]
When closing #77, notice that selecting a particular sequence (by button) causes duplicate text to appear.

It disappears if window is resized.  Also after "Calculate" button is pressed.

**Comment by maxieds** [comment]
@ceheitsch 
Please be more verbose in how to reproduce the bugs you see. Can you provide step-by-step instructions for how to see what I am supposed to fix? Thanks.

**Comment by maxieds** [comment]
@ceheitsch 
Was the duplicate text on the sides of the plots, or overlayed bold versus non-bold text in this region:

![Screenshot from 2020-01-28 12-44-19](https://user-images.githubusercontent.com/22165688/73290189-04547880-41cc-11ea-9dab-b8096ddd27d7.png)

If it's the latter, I believe that it is fixed when I recompiled to the latest FLTK 1.4.x. I will go ahead and update the brew package to use the newest source just in case.

**Comment by maxieds** [comment]
@ceheitsch 
It should be fixed. Ideally FLTK should be handling redrawing the labels, but with some careful resetting of the labels to the empty string before changing the fonts (bold, unbold), we get the desired behavior anyway:

![Screenshot from 2020-01-28 19-44-15](https://user-images.githubusercontent.com/22165688/73318315-00921780-4207-11ea-97c1-5f105f7e6cf9.png)

**Comment by maxieds** [comment]
Mac OSX 10.14.x support verified!
