### ISSUE TITLE
List of TODO features...

### ISSUE THREAD

**Issue by maxieds** [gtDMMB/RNAStructViz#8]
* Add a configurations box to set, for example, the scheme/FLTK theme used by the app. The nice "gtk+" version became ugly after I reset my Linux box's theme. We should give the users some customization options here.

**Comment by maxieds** [comment]
One of the main things that was bothering me about the app is how non-descript the features are. That is, until someone shows you that it does something, it's not at all clear that it does it... So to help users navigate the app, I added some more user friendly touches. See the attached screenshot.

![screenshot at 2018-10-21 08-30-22](https://user-images.githubusercontent.com/22165688/47266980-9a025200-d50b-11e8-85bf-d7d76e19ee8f.png)

Perhaps I should add some instructions above the "Diagram" and "Statistics" buttons too?

**Comment by maxieds** [comment]
And done... 

![screenshot at 2018-10-21 09-04-50](https://user-images.githubusercontent.com/22165688/47267342-683fba00-d510-11e8-82f6-b84e5782be28.png)

**Comment by maxieds** [comment]
As @annakirkpatrick pointed out this theme seems native to my local Linux install. The "Config Options" button added to the actions section of the program should allow users to set their preferred theme to whichever one they see fit.

**Comment by maxieds** [comment]
After some work and tweaking with options, I came up with a better "standard" theme.

![screenshot at 2018-10-21 14-35-32](https://user-images.githubusercontent.com/22165688/47270780-ac49b380-d53e-11e8-8a09-7b24265be7c1.png)

**Comment by maxieds** [comment]
@annakirkpatrick @gtDMMB/rnastructviz-development Not sure where the previous posts were directed, but they showed up on my screen... Here's the purple / lavender scheme you suggested:

![screenshot at 2018-10-21 22-21-06](https://user-images.githubusercontent.com/22165688/47275732-cb1c6a00-d57f-11e8-9748-d872345c149f.png)

**Comment by annakirkpatrick** [comment]
@maxieds Glad to see you got the screenshots into the issue thread; no idea what happened. I like both the purple and the green better than the original aqua. Do we also have the ability to change the background color easily? I'm thinking the grey background looks off with the much whiter text. I'd like to experiment with colors if it's not too hard.
