### ISSUE TITLE
Misalignment of arcs and ticks on circle

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#85]
The attached structure (o.nivara_region_25.dot with txt extension b/c of github) is unusually sparse, so it's easy to see that the arcs for the base pairs are misaligned in the screen shot.

For instance, there is a base pair (29,41) in the ct file, but in the diagram window it looks like (30, 42+).
[o.nivara_region_25.dot.txt](https://github.com/gtDMMB/RNAStructViz/files/4110124/o.nivara_region_25.dot.txt)
![Screen Shot 2020-01-24 at 1 48 19 PM](https://user-images.githubusercontent.com/43553267/73095528-d233d580-3eb0-11ea-8b33-a4ebebf1d7fa.png)

**Comment by maxieds** [comment]
@ceheitsch 
I believe that part of the problem (was) is in the ``DiagramWindow::ComputeDiagramParams`` function where we had semi-arbitrary offsets:
```cpp
angleDelta = (M_PI * 2.0f - 0.05f) / (float) numBases;
angleBase = 1.5f * M_PI - 0.025f;
radius = (resolution + 10.f) / 2.0f;
```
Also, there was some issue with rounding error. When I increase the number of ticks around the circle from **12** to **35**, we get the following diagram, which seems to be more consistent with your example:

![Screenshot at 2020-01-27 22-39-15](https://user-images.githubusercontent.com/22165688/73233909-024fd280-4156-11ea-930a-2bfd1ea79bea.png)

So the question is this: *Do we increase the number of tick marks around the bounding circle to prevent this from happening?*

**Comment by maxieds** [comment]
@ceheitsch 
RE: The question asked above. Here is the arc diagram with **27** ticks. A little more packed, for sure, but shows your requested accuracy. *Is this an OK number of bounding ticks?*

![Screenshot at 2020-01-27 22-43-16](https://user-images.githubusercontent.com/22165688/73234070-96219e80-4156-11ea-88bf-701bf95d08b8.png)

**Comment by maxieds** [comment]
Mac OSX 10.14.x support verified!

**Comment by maxieds** [comment]
@ceheitsch 

I'm about to add the new ``brew`` release to lower the former number of tick marks (27) around the arc diagram bounding circle to **12** as we originally discussed. The documentation of the accuracy (lack thereof) of these tick marks in determining precise base arc end indices is now [here](https://github.com/gtDMMB/RNAStructViz/wiki/KnownLimitations#8-accuracy-of-the-tick-marks-in-the-arc-diagram-viewer-window) on the known issues page of the WIKI. 

Please close this issue once you are happy with it.
