### ISSUE TITLE
Test of with-cairo on common linux distros

### ISSUE THREAD

**Issue by annakirkpatrick** [gtDMMB/RNAStructViz#9]
Maxie and I discovered some significant discrepancies in graphics and library location behaviors on my older 32 bit Ubuntu 14.04 Linux machine compared to her 64-bit latest-release Linux mint machine. Given that these two distributions are actually pretty closely related, we agreed that we need to do some testing on a sampling of the most popular Linux distributions.

I'm opening this issue for the sake of tracking our progress.

Based on a quick perusal of some top Linux distribution lists online (getting exact numbers is basically impossible), I propose that we should test on the following.

1. older, 32-bit Ubuntu (my machine)
2. Up-to-date Linux mint (Maxie's machine)
3. Up-to-date Ubuntu
4. Up-to-date CentOS
5. Up-to-date OpenSUSE
6. Up-to-date Arch

This testing is not urgent; it can be completed anytime before the paper is published, and any necessary fixes will likely be minimal. 

I have a desktop system largely unused with a large hard drive. I can install the Ubuntu, Fedora, and OpenSUSE, and Debian distributions (maybe not all at once). Maxie, you are responsible for Arch.

**Comment by annakirkpatrick** [comment]
Today, Maxie tested CentOS, and I tested Ubuntu. Software compiles and runs successfully on both.

I have updated the README to reflect the exact procedure for installing on modern Ubuntu.

**Comment by maxieds** [comment]
I think we have handled this sufficiently by now. Closing to clean up the issues tracking page...
