### ISSUE TITLE
ordering of sequences in statistics window

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#90]
Under "Structures for Comparison" there is a list of sequences, and under "Predicted Structures" there is a second list --- in what appears to be in the reverse order of the first.    In the attached picture, the first list starts "o.nivara_region_01.dot, o.nivara_region_02.dot, ..."  while the second is "o.nivara_region_37, o.nivara_region_36, ..."

Please change the second "Predicted Structures" so that it matches the first "Structures for Comparison" list.   This will/should also change the order in which the data is listed in the histograms.  Thanks.
![Screen Shot 2020-03-11 at 12 37 14 PM](https://user-images.githubusercontent.com/43553267/76441411-bbc8d700-6395-11ea-830e-0616440525f7.png)

**Comment by maxieds** [comment]
@ceheitsch 
Please upgrade to **v2.3.5-testing** to see and test the changes.

**Comment by ceheitsch** [comment]
Right and left lists are now ordered the same (top to bottom), but the histograms are still ordered right to left rather than left to right.  In the attached screenshot, the histograms read from left to right as max, clique6, ..., clique1, T99 which is confusing when the list reads (top to bottom) as T99, clique1, ..., clique6, max.  
<img width="1180" alt="Screen Shot 2020-05-18 at 10 57 18 AM" src="https://user-images.githubusercontent.com/43553267/82228236-e3d53900-98f6-11ea-9eed-b30f9e77f4d4.png">

**Comment by maxieds** [comment]
@ceheitsch 
This issue should be fixed in the forthcoming release version **v2.3.7-testing** (to be released in conjunction with fixes for the remaining recent issues commented on). See the fix demonstrated in the following screenshot:

![Screen Shot 2020-05-19 at 11 18 44 AM](https://user-images.githubusercontent.com/22165688/82345071-d6858080-99c2-11ea-8bd9-469ee85f4b1d.png)

**Comment by ceheitsch** [comment]
All sorted!
