### ISSUE TITLE
coloring of sequences in statistics window

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#91]
Today I'm using RNAStructViz to analyze predictions so am finding a few improvements which can be made.  In the statistics window (included) if there are "too many" sequence then the colors are so dark that the legends can't be read.  It also becomes hard to distinguish between dark greens, etc.  One option is to 'recycle' colors for the legends
![Screen Shot 2020-03-11 at 12 37 14 PM](https://user-images.githubusercontent.com/43553267/76441726-44477780-6396-11ea-8235-1a9422e9b3d1.png)
, but there may be others.

**Comment by ceheitsch** [comment]
Which symbols are used for the ROC plot need to be (re)considered with alterations to the coloring scheme.  In the attached picture, all the similar (very dark) colors have the same circle symbol.
![Screen Shot 2020-03-11 at 12 57 01 PM](https://user-images.githubusercontent.com/43553267/76442899-fa5f9100-6397-11ea-80d2-18b83a844f9d.png)

**Comment by maxieds** [comment]
@ceheitsch
I believe that there was a bug where the colors (of the seven that are defined) get darkened every time after seven bars, as opposed once every seven thereafter. The release **v2.3.5** should fix this issue. Please test after I release the new brew formula.

**Comment by ceheitsch** [comment]
Colors now cycling nicely!
