### ISSUE TITLE
Adjust "Raw Sequence Data" spacing

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#93]
It would be better if the spacing for the "Raw Sequence Data" in the ct file viewer were every 10 nucleotides.  So instead of:
GGCGGCGU AGCUCAGC UGGCUAGA GCAUGCGG UUCAUACC CGCAGUGU CCGGGGUU CGAGUCCC
It would be:
GGCGGCGUAG CUCAGCUGGC UAGAGCAUGC etc.

**Comment by maxieds** [comment]
Done in the latest release: 

![Screen Shot 2020-03-30 at 1 28 38 PM](https://user-images.githubusercontent.com/22165688/77943136-bcfd6d80-728a-11ea-9b91-2e65cfde281e.png)

**Comment by ceheitsch** [comment]
Easier to parse; thanks.
