### ISSUE TITLE
triple intersection counts not correct

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#94]
The T99.dot prediction has 12 TP, 14 FP, and 10 FP when compared to the native AE014184_h.nopct structure.  The T99.dot and clique2.dot predictions are the same.  The two pairwise comparisons are correct, but the counts in the triple comparison have the 14FP base pairs split differently between T99.dot and clique2.dot structures.

<img width="880" alt="Screen Shot 2020-05-18 at 12 01 22 PM" src="https://user-images.githubusercontent.com/43553267/82234331-4c281880-98ff-11ea-9de7-0ca1af454547.png">
[AE014184_h.nopct.txt](https://github.com/gtDMMB/RNAStructViz/files/4645243/AE014184_h.nopct.txt)
[T99.dot.txt](https://github.com/gtDMMB/RNAStructViz/files/4645244/T99.dot.txt)
[AE014184_h.nopct.txt](https://github.com/gtDMMB/RNAStructViz/files/4645245/AE014184_h.nopct.txt)
<img width="881" alt="Screen Shot 2020-05-18 at 11 54 30 AM" src="https://user-images.githubusercontent.com/43553267/82233660-5695e280-98fe-11ea-9573-7939762aaf72.png">
<img width="880" alt="Screen Shot 2020-05-18 at 11 54 51 AM" src="https://user-images.githubusercontent.com/43553267/82233691-6281a480-98fe-11ea-9920-75bd096c5e0f.png">

**Comment by maxieds** [comment]
@ceheitsch 
You didn't provide the link for the *clique2.dot* file. I am currently unable to test out and resolve the issue with the special case you pointed out above.

**Comment by ceheitsch** [comment]
Sorry about that!  It seems that I loaded the nopct file twice.  Clique2.dot now included.  
[clique2.dot.txt](https://github.com/gtDMMB/RNAStructViz/files/4683361/clique2.dot.txt)

**Comment by maxieds** [comment]
@ceheitsch 
I'm not entirely sure I'm understanding the split problem well. Does this fix it? 

![Screen Shot 2020-05-28 at 3 13 13 AM](https://user-images.githubusercontent.com/22165688/83110560-406feb00-a091-11ea-8f82-4b27773ce6de.png)

**Comment by ceheitsch** [comment]
Seems to be fixed now.
