### ISSUE TITLE
xml button

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#97]
Noticed that the xml button says "...is disabled in this testing release."   Probably best to remove button if feature hasn't been fully developed and tested at this point.

**Comment by maxieds** [comment]
@ceheitsch 
I actually looked through the issues last week, thought about implementing the XML export, and then decided against it for now. It's going to be trouble to test as we should support this format as (yet another) input format if we are going to expect users to save to it. It was a nice thought. Let's just leave this as an open [feaure request issue (#64)](https://github.com/gtDMMB/RNAStructViz/issues/64) for now. The next release should have this button removed, but I'm going to keep some source files that implemented it in the tree so we can refer to them later.

**Comment by maxieds** [comment]
@ceheitsch 
The XML button is now not instantiated in the live code. The resulting button layout is the following:

![Screen Shot 2020-07-31 at 4 01 41 PM](https://user-images.githubusercontent.com/22165688/89072807-4612d700-d347-11ea-91f8-919813b74f65.png)

**Comment by ceheitsch** [comment]
Sounds like a good plan.
